import fs from 'fs';

const filepath = 'src/data/npcs.js';
let content = fs.readFileSync(filepath, 'utf8');

const replacements = {
  // CHLOE
  [`    { id: "chloe_intro", type: "introduction", minRelationship: 0, title: "Paint and Silence", prompt: "Chloe is sketching you in a cafe but tries to hide the notebook when you notice.", emotionalBeat: "Quiet observation and fear of intrusion.", choices: [{ text: "Ask to see the sketch without judging it.", relationshipImpact: 8, chemistryImpact: 7 }, { text: "Pose dramatically for her.", relationshipImpact: 6, chemistryImpact: 9, unlocksMemory: "chloe_playful_pose" }, { text: "Pretend you didn't see anything.", checkStat: "empathy", threshold: 30, onSuccess: { relationshipImpact: 5, chemistryImpact: 3 }, onFail: { relationshipImpact: -2, chemistryImpact: -1 } }] },`]:
  `    { id: "chloe_intro", type: "introduction", minRelationship: 0, title: "Paint and Silence", prompt: "Chloe is sketching you in a cafe. When you notice, she immediately tries to hide the notebook, her quiet observation masking a deep fear of intrusion.", emotionalBeat: "Quiet observation and fear of intrusion.", choices: [{ text: "Ask to see the sketch without judging it.", relationshipImpact: 8, chemistryImpact: 7, unlocksMemory: "chloe_shared_sketch" }, { text: "Pose dramatically for her to break the ice.", relationshipImpact: 6, chemistryImpact: 9, unlocksMemory: "chloe_playful_pose" }, { text: "Pretend you didn't see anything, giving her space.", checkStat: "empathy", threshold: 30, onSuccess: { relationshipImpact: 5, chemistryImpact: 3, unlocksMemory: "chloe_respectful_distance" }, onFail: { relationshipImpact: -2, chemistryImpact: -1, futureCallback: "chloe_awkward_silence" } }] },`,

  [`    { id: "chloe_early", type: "early connection", minRelationship: 18, title: "Open Mic Nerves", prompt: "She wants to perform but freezes backstage.", emotionalBeat: "Insecurity beneath artistry.", choices: [{ text: "Hold her hand and breathe together.", relationshipImpact: 8, chemistryImpact: 9 }, { text: "Offer a grounding ritual where she picks your role backstage.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "chloe_backstage_ritual" }, { text: "Push her on stage before she overthinks.", relationshipImpact: 1, chemistryImpact: 0 }] },`]:
  `    { id: "chloe_early", type: "early connection", minRelationship: 18, title: "Open Mic Nerves", prompt: "She wants to perform but completely freezes backstage. Her insecurity threatens to swallow her artistry whole unless someone grounds her.", emotionalBeat: "Insecurity beneath artistry.", choices: [{ text: "Hold her hand and breathe together in the dark.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "chloe_grounded_backstage" }, { text: "Offer a grounding ritual where she picks your role.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "chloe_backstage_ritual" }, { text: "Push her on stage before she overthinks.", relationshipImpact: 1, chemistryImpact: 0, futureCallback: "chloe_stage_fright" }] },`,

  [`    { id: "chloe_reveal", type: "personal reveal", minRelationship: 35, title: "Critic's Review", prompt: "A harsh review makes Chloe question whether she is a fraud.", emotionalBeat: "Artistic intensity turning inward.", choices: [{ text: "Read the review together and separate signal from cruelty.", relationshipImpact: 9, chemistryImpact: 8, unlocksMemory: "chloe_shared_review" }, { text: "Ask her to paint the feeling before discussing it.", relationshipImpact: 7, chemistryImpact: 8 }, { text: "Ignore critics completely.", checkStat: "confidence", threshold: 30, onSuccess: { relationshipImpact: 5, chemistryImpact: 4 }, onFail: { relationshipImpact: 0, chemistryImpact: -1 } }] },`]:
  `    { id: "chloe_reveal", type: "personal reveal", minRelationship: 35, title: "Critic's Review", prompt: "A harsh review makes Chloe spiral, questioning whether she is a complete fraud. The artistic intensity she usually channels into her work is now turned painfully inward.", emotionalBeat: "Artistic intensity turning inward.", choices: [{ text: "Read the review together and separate signal from cruelty.", relationshipImpact: 9, chemistryImpact: 8, unlocksMemory: "chloe_shared_review" }, { text: "Ask her to paint the feeling before discussing it.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "chloe_painted_feeling" }, { text: "Tell her to ignore critics completely.", checkStat: "confidence", threshold: 30, onSuccess: { relationshipImpact: 5, chemistryImpact: 4, unlocksMemory: "chloe_ignored_critic" }, onFail: { relationshipImpact: 0, chemistryImpact: -1, futureCallback: "chloe_doubt_lingers" } }] },`,

  [`    { id: "chloe_conflict", type: "conflict", minRelationship: 52, title: "Canceled Session", prompt: "You miss a promised gallery walk and she paints over the piece she made for you.", emotionalBeat: "Abandonment trigger.", choices: [{ text: "Dismiss it as dramatic.", relationshipImpact: -7, chemistryImpact: -6 }, { text: "Apologize and ask to hear the hurt fully.", relationshipImpact: 8, chemistryImpact: 8, futureCallback: "chloe_repaint_together" }, { text: "Offer to sit quietly while she decides what to salvage.", relationshipImpact: 5, chemistryImpact: 6, unlocksMemory: "chloe_repair_presence" }] },`]:
  `    { id: "chloe_conflict", type: "conflict", minRelationship: 52, title: "Canceled Session", prompt: "You miss a promised gallery walk and she immediately paints over the piece she made for you. The destruction is a raw, devastating abandonment trigger.", emotionalBeat: "Abandonment trigger.", choices: [{ text: "Dismiss her reaction as being overly dramatic.", relationshipImpact: -7, chemistryImpact: -6, futureCallback: "chloe_painted_over" }, { text: "Apologize and ask to hear the hurt fully, no defense.", relationshipImpact: 8, chemistryImpact: 8, futureCallback: "chloe_repaint_together" }, { text: "Offer to sit quietly while she decides what to salvage.", relationshipImpact: 5, chemistryImpact: 6, unlocksMemory: "chloe_repair_presence" }] },`,

  // RINA
  [`    { id: "rina_intro", type: "introduction", minRelationship: 0, title: "After-Hours Jazz", prompt: "Rina invites you to a tiny jazz basement after her shift ends.", emotionalBeat: "Composed charm with playful tests.", choices: [{ text: "Ask her to choose the first song and lead the vibe.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "rina_sets_the_tone" }, { text: "Tell a polished story to impress her.", relationshipImpact: 5, chemistryImpact: 5 }, { text: "Order for both of you with confidence.", checkStat: "charisma", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 7 }, onFail: { relationshipImpact: -2, chemistryImpact: -2 } }] },`]:
  `    { id: "rina_intro", type: "introduction", minRelationship: 0, title: "After-Hours Jazz", prompt: "Rina invites you to a tiny jazz basement after her shift ends. She watches you carefully over her glass, her composed charm laced with playful tests.", emotionalBeat: "Composed charm with playful tests.", choices: [{ text: "Ask her to choose the first song and lead the vibe.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "rina_sets_the_tone" }, { text: "Tell a polished story to impress her.", relationshipImpact: 5, chemistryImpact: 5, unlocksMemory: "rina_heard_story" }, { text: "Order for both of you with confidence.", checkStat: "charisma", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 7, unlocksMemory: "rina_likes_confidence" }, onFail: { relationshipImpact: -2, chemistryImpact: -2, futureCallback: "rina_unimpressed" } }] },`,

  [`    { id: "rina_early", type: "early connection", minRelationship: 18, title: "The VIP", prompt: "A demanding VIP tries to buy her attention while you are there.", emotionalBeat: "Guarding independence.", choices: [{ text: "Let her handle it and compliment her tact afterward.", relationshipImpact: 8, chemistryImpact: 7, unlocksMemory: "rina_respects_autonomy" }, { text: "Step in and pretend to be her manager.", relationshipImpact: 6, chemistryImpact: 6, futureCallback: "rina_fake_manager_joke" }, { text: "Get jealous and start a scene.", relationshipImpact: -4, chemistryImpact: -2 }] },`]:
  `    { id: "rina_early", type: "early connection", minRelationship: 18, title: "The VIP", prompt: "A demanding VIP tries to buy her attention while you are there. She handles it with a razor-sharp smile, fiercely guarding her independence.", emotionalBeat: "Guarding independence.", choices: [{ text: "Let her handle it and compliment her ruthless tact afterward.", relationshipImpact: 8, chemistryImpact: 7, unlocksMemory: "rina_respects_autonomy" }, { text: "Step in and playfully pretend to be her manager.", relationshipImpact: 6, chemistryImpact: 6, futureCallback: "rina_fake_manager_joke" }, { text: "Get genuinely jealous and start a scene.", relationshipImpact: -4, chemistryImpact: -2, futureCallback: "rina_jealousy_scene" }] },`,

  [`    { id: "rina_reveal", type: "personal reveal", minRelationship: 35, title: "Family Ledger", prompt: "Rina admits she sends most of her income home and feels trapped between duty and desire.", emotionalBeat: "Pride mixed with fatigue.", choices: [{ text: "You can be devoted and still choose joy.", relationshipImpact: 9, chemistryImpact: 8, unlocksMemory: "rina_shared_burden" }, { text: "Build a practical budget and a small freedom fund together.", relationshipImpact: 7, chemistryImpact: 7 }, { text: "Push for a risky all-in career leap.", checkStat: "finance", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 4 }, onFail: { relationshipImpact: -3, chemistryImpact: -2 } }] },`]:
  `    { id: "rina_reveal", type: "personal reveal", minRelationship: 35, title: "Family Ledger", prompt: "Rina admits she sends most of her income home. She looks away, her usual polished pride mixed with an exhausting fatigue, feeling trapped between duty and desire.", emotionalBeat: "Pride mixed with fatigue.", choices: [{ text: "Tell her she can be devoted to them and still choose joy.", relationshipImpact: 9, chemistryImpact: 8, unlocksMemory: "rina_shared_burden" }, { text: "Build a practical budget and a small freedom fund together.", relationshipImpact: 7, chemistryImpact: 7, unlocksMemory: "rina_freedom_fund" }, { text: "Push her for a risky all-in career leap.", checkStat: "finance", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 4, unlocksMemory: "rina_career_pushed" }, onFail: { relationshipImpact: -3, chemistryImpact: -2, futureCallback: "rina_felt_pressured" } }] },`,

  [`    { id: "rina_conflict", type: "conflict", minRelationship: 52, title: "Unread Message", prompt: "She goes quiet for two days after a family emergency and returns distant.", emotionalBeat: "Withdrawal when overwhelmed.", choices: [{ text: "Demand immediate explanations.", relationshipImpact: -7, chemistryImpact: -5 }, { text: "Tell her you'll listen when she's ready and mean it.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "rina_safe_silence" }, { text: "Leave a short voice note and one practical offer of help.", relationshipImpact: 5, chemistryImpact: 6, futureCallback: "rina_voice_note_thread" }] },`]:
  `    { id: "rina_conflict", type: "conflict", minRelationship: 52, title: "Unread Message", prompt: "She goes quiet for two days after a family emergency and returns distant. The withdrawal is sudden and sharp when she gets overwhelmed.", emotionalBeat: "Withdrawal when overwhelmed.", choices: [{ text: "Demand immediate explanations for the silence.", relationshipImpact: -7, chemistryImpact: -5, futureCallback: "rina_pushed_away" }, { text: "Tell her you'll listen when she's ready, and mean it.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "rina_safe_silence" }, { text: "Leave a short voice note and one practical offer of help.", relationshipImpact: 5, chemistryImpact: 6, futureCallback: "rina_voice_note_thread" }] },`,

  // MAYA
  [`    { id: "maya_intro", type: "introduction", minRelationship: 0, title: "Rooftop Lens", prompt: "Maya, a bisexual documentary photographer, asks if you prefer to be seen or hidden.", emotionalBeat: "Direct curiosity and fearless honesty.", choices: [{ text: "Seen, but only by someone who really pays attention.", relationshipImpact: 9, chemistryImpact: 9, unlocksMemory: "maya_sees_player_clearly" }, { text: "Let her frame your first portrait shot.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "maya_first_portrait" }, { text: "Deflect with jokes.", checkStat: "charisma", threshold: 30, onSuccess: { relationshipImpact: 4, chemistryImpact: 4 }, onFail: { relationshipImpact: -2, chemistryImpact: -2 } }] },`]:
  `    { id: "maya_intro", type: "introduction", minRelationship: 0, title: "Rooftop Lens", prompt: "Maya points her lens at the skyline before turning it directly on you. With fearless honesty, she asks if you prefer to be seen or hidden.", emotionalBeat: "Direct curiosity and fearless honesty.", choices: [{ text: "Tell her you want to be seen, but only by someone who pays attention.", relationshipImpact: 9, chemistryImpact: 9, unlocksMemory: "maya_sees_player_clearly" }, { text: "Let her frame your first portrait shot right there.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "maya_first_portrait" }, { text: "Deflect her intense gaze with jokes.", checkStat: "charisma", threshold: 30, onSuccess: { relationshipImpact: 4, chemistryImpact: 4, unlocksMemory: "maya_amused_by_jokes" }, onFail: { relationshipImpact: -2, chemistryImpact: -2, futureCallback: "maya_felt_deflected" } }] },`,

  [`    { id: "maya_early", type: "early connection", minRelationship: 18, title: "Street Interview", prompt: "Her interview subject bails, and she asks you to step in for a practice run.", emotionalBeat: "Creative urgency with soft vulnerability.", choices: [{ text: "Answer honestly and stay grounded.", relationshipImpact: 8, chemistryImpact: 8 }, { text: "Let her direct the whole scene while you stay present.", relationshipImpact: 6, chemistryImpact: 8, futureCallback: "maya_director_dynamic" }, { text: "Try to control the interview flow.", relationshipImpact: -1, chemistryImpact: 1 }] },`]:
  `    { id: "maya_early", type: "early connection", minRelationship: 18, title: "Street Interview", prompt: "Her interview subject bails abruptly. She asks you to step in for a practice run, her creative urgency laced with a soft, sudden vulnerability.", emotionalBeat: "Creative urgency with soft vulnerability.", choices: [{ text: "Answer her questions honestly, staying entirely grounded.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "maya_honest_interview" }, { text: "Let her direct the whole scene while you just stay present.", relationshipImpact: 6, chemistryImpact: 8, futureCallback: "maya_director_dynamic" }, { text: "Try to control the interview flow yourself.", relationshipImpact: -1, chemistryImpact: 1, futureCallback: "maya_power_struggle" }] },`,

  [`    { id: "maya_reveal", type: "personal reveal", minRelationship: 35, title: "The Cut Room", prompt: "Maya admits she avoids long-term relationships because she fears losing herself.", emotionalBeat: "Longing underneath self-protection.", choices: [{ text: "You don't need to shrink to stay loved.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "maya_identity_safe" }, { text: "Set boundaries that protect both of your autonomy.", relationshipImpact: 7, chemistryImpact: 7 }, { text: "Promise intensity without structure.", checkStat: "empathy", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 5 }, onFail: { relationshipImpact: -3, chemistryImpact: -2 } }] },`]:
  `    { id: "maya_reveal", type: "personal reveal", minRelationship: 35, title: "The Cut Room", prompt: "Surrounded by photos, Maya admits she avoids long-term relationships because she fears losing her edge. The self-protection barely hides a deep, quiet longing.", emotionalBeat: "Longing underneath self-protection.", choices: [{ text: "Tell her she doesn't need to shrink to stay loved.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "maya_identity_safe" }, { text: "Set boundaries that protect both of your autonomy.", relationshipImpact: 7, chemistryImpact: 7, unlocksMemory: "maya_autonomy_protected" }, { text: "Promise intensity without rigid structure.", checkStat: "empathy", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 5, unlocksMemory: "maya_intensity_promised" }, onFail: { relationshipImpact: -3, chemistryImpact: -2, futureCallback: "maya_felt_smothered" } }] },`,

  [`    { id: "maya_conflict", type: "conflict", minRelationship: 52, title: "Published Without Warning", prompt: "Maya posts a candid photo of you that sparks attention before checking in.", emotionalBeat: "Freedom vs. intimacy boundaries.", choices: [{ text: "Publicly call her out.", relationshipImpact: -7, chemistryImpact: -6 }, { text: "Tell her privately what trust needs to look like.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "maya_respects_boundaries" }, { text: "Ask for a review rule before future posts.", relationshipImpact: 6, chemistryImpact: 6, futureCallback: "maya_editorial_rulebook" }] },`]:
  `    { id: "maya_conflict", type: "conflict", minRelationship: 52, title: "Published Without Warning", prompt: "Maya posts a candid, highly intimate photo of you that sparks attention before checking in. Her drive for freedom collides painfully with your boundaries.", emotionalBeat: "Freedom vs. intimacy boundaries.", choices: [{ text: "Publicly call her out in the comments.", relationshipImpact: -7, chemistryImpact: -6, futureCallback: "maya_public_argument" }, { text: "Tell her privately what trust needs to look like for you.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "maya_respects_boundaries" }, { text: "Ask for a strict review rule before future posts.", relationshipImpact: 6, chemistryImpact: 6, futureCallback: "maya_editorial_rulebook" }] },`,

  // NORA
  [`    { id: "nora_intro", type: "introduction", minRelationship: 0, title: "Kitchen Timing", prompt: "Nora, a pastry chef, asks if you trust recipes or instincts.", emotionalBeat: "Warm discipline and playful control.", choices: [{ text: "Teach me your exact method.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "nora_recipe_apprentice" }, { text: "Let's improvise and taste as we go.", relationshipImpact: 6, chemistryImpact: 7 }, { text: "Pretend expertise you don't have.", checkStat: "culinary", threshold: 35, onSuccess: { relationshipImpact: 5, chemistryImpact: 5 }, onFail: { relationshipImpact: -2, chemistryImpact: -2 } }] },`]:
  `    { id: "nora_intro", type: "introduction", minRelationship: 0, title: "Kitchen Timing", prompt: "Nora stands in the kitchen, wiping flour off her apron. With warm discipline and playful control, she asks if you trust recipes or pure instinct.", emotionalBeat: "Warm discipline and playful control.", choices: [{ text: "Ask her to teach you her exact method.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "nora_recipe_apprentice" }, { text: "Suggest improvising and tasting as you go.", relationshipImpact: 6, chemistryImpact: 7, unlocksMemory: "nora_improviser" }, { text: "Pretend you have culinary expertise.", checkStat: "culinary", threshold: 35, onSuccess: { relationshipImpact: 5, chemistryImpact: 5, unlocksMemory: "nora_impressed_by_skills" }, onFail: { relationshipImpact: -2, chemistryImpact: -2, futureCallback: "nora_caught_bluffing" } }] },`,

  [`    { id: "nora_early", type: "early connection", minRelationship: 18, title: "Before Sunrise Prep", prompt: "She invites you to prep croissants at 4AM to see if you can handle her pace.", emotionalBeat: "Tenderness hidden inside rigor.", choices: [{ text: "Show up early and follow her system.", relationshipImpact: 8, chemistryImpact: 8 }, { text: "Ask her to assign you one station and own it.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "nora_station_trust" }, { text: "Complain about the schedule.", relationshipImpact: -3, chemistryImpact: -2 }] },`]:
  `    { id: "nora_early", type: "early connection", minRelationship: 18, title: "Before Sunrise Prep", prompt: "She invites you to prep croissants at 4AM, a ruthless test to see if you can handle her pace. But watching her fold butter reveals a tenderness hidden inside her rigor.", emotionalBeat: "Tenderness hidden inside rigor.", choices: [{ text: "Show up early, caffeine in hand, and follow her system.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "nora_morning_discipline" }, { text: "Ask her to assign you one station and own it completely.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "nora_station_trust" }, { text: "Complain about the brutal schedule.", relationshipImpact: -3, chemistryImpact: -2, futureCallback: "nora_disappointed_in_lazy" }] },`,

  [`    { id: "nora_reveal", type: "personal reveal", minRelationship: 35, title: "Burnt Batch", prompt: "Nora confesses she still hears an old mentor telling her she's never enough.", emotionalBeat: "Perfectionism cracking open.", choices: [{ text: "You are not your worst batch.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "nora_self_criticism_shared" }, { text: "Write a recovery plan together for bad service days.", relationshipImpact: 7, chemistryImpact: 7 }, { text: "Tell her to toughen up and ignore it.", checkStat: "confidence", threshold: 40, onSuccess: { relationshipImpact: 3, chemistryImpact: 3 }, onFail: { relationshipImpact: -4, chemistryImpact: -3 } }] },`]:
  `    { id: "nora_reveal", type: "personal reveal", minRelationship: 35, title: "Burnt Batch", prompt: "Staring at a ruined batch of macarons, Nora confesses she still hears an old mentor telling her she's never enough. The flawless perfectionism finally cracks open.", emotionalBeat: "Perfectionism cracking open.", choices: [{ text: "Tell her she is not her worst batch.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "nora_self_criticism_shared" }, { text: "Write a recovery plan together for bad service days.", relationshipImpact: 7, chemistryImpact: 7, unlocksMemory: "nora_recovery_plan" }, { text: "Tell her to toughen up and ignore the past.", checkStat: "confidence", threshold: 40, onSuccess: { relationshipImpact: 3, chemistryImpact: 3, unlocksMemory: "nora_tough_love" }, onFail: { relationshipImpact: -4, chemistryImpact: -3, futureCallback: "nora_felt_invalidated" } }] },`,

  [`    { id: "nora_conflict", type: "conflict", minRelationship: 52, title: "Missed Anniversary Service", prompt: "Nora chooses a critical service over your planned night and expects you to understand.", emotionalBeat: "Duty colliding with intimacy.", choices: [{ text: "Say work always wins and shut down.", relationshipImpact: -7, chemistryImpact: -5 }, { text: "Name what hurt and ask for a make-up ritual.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "nora_repair_ritual" }, { text: "Show up after service with food and clear boundaries for next time.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "nora_after_service_rule" }] },`]:
  `    { id: "nora_conflict", type: "conflict", minRelationship: 52, title: "Missed Anniversary Service", prompt: "Nora chooses a critical service over your planned night out, stubbornly expecting you to just understand. Her duty collides painfully with your need for intimacy.", emotionalBeat: "Duty colliding with intimacy.", choices: [{ text: "Say work always wins and coldly shut down.", relationshipImpact: -7, chemistryImpact: -5, futureCallback: "nora_cold_shoulder" }, { text: "Name what hurt and ask for a make-up ritual.", relationshipImpact: 8, chemistryImpact: 8, unlocksMemory: "nora_repair_ritual" }, { text: "Show up after service with food and clear boundaries for next time.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "nora_after_service_rule" }] },`
};

for (const [key, value] of Object.entries(replacements)) {
  if (!content.includes(key)) {
    console.error("COULD NOT FIND:", key.substring(0, 100));
  } else {
    content = content.replace(key, value);
  }
}

fs.writeFileSync(filepath, content);
console.log("Updated Chloe, Rina, Maya, and Nora.");
