import fs from 'fs';

const filepath = 'src/data/npcs.js';
let content = fs.readFileSync(filepath, 'utf8');

const replacements = {
  // ELENA
  [`    { id: "elena_intro", type: "introduction", minRelationship: 0, title: "A Question About Books", prompt: "Elena asks what kind of books you read when no one is judging you.", emotionalBeat: "Guarded curiosity with a hint of playful authority.", choices: [{ text: "I read to feel less alone.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "elena_knows_player_reads" }, { text: "Recommend me your strictest reading assignment.", relationshipImpact: 6, chemistryImpact: 8, unlocksMemory: "elena_assigns_reading", futureCallback: "elena_book_club_dynamic" }, { text: "I read whatever makes me look smart.", checkStat: "intelligence", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 4 }, onFail: { relationshipImpact: -2, chemistryImpact: -1 } }], futureCallback: "elena_poetry_binder" },`]:
  `    { id: "elena_intro", type: "introduction", minRelationship: 0, title: "A Question About Books", prompt: "Elena looks up from her notes, her guarded curiosity meeting yours. 'What kind of books do you read when no one is judging you?'", emotionalBeat: "Guarded curiosity with a hint of playful authority.", choices: [{ text: "I read to feel less alone.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "elena_knows_player_reads" }, { text: "Recommend me your strictest reading assignment.", relationshipImpact: 6, chemistryImpact: 8, unlocksMemory: "elena_assigns_reading", futureCallback: "elena_book_club_dynamic" }, { text: "I read whatever makes me look smart.", checkStat: "intelligence", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 4, unlocksMemory: "elena_impressed_by_wit" }, onFail: { relationshipImpact: -2, chemistryImpact: -1, futureCallback: "elena_intellectual_flaw" } }], futureCallback: "elena_poetry_binder" },`,

  [`    { id: "elena_early", type: "early connection", minRelationship: 18, title: "Library Closing Time", prompt: "She is racing a deadline as security closes the library.", emotionalBeat: "Academic pressure and fear of losing control.", choices: [{ text: "Stay and help organize citations.", relationshipImpact: 7, chemistryImpact: 6 }, { text: "Set a timer and make her take a tea break first.", relationshipImpact: 5, chemistryImpact: 7, unlocksMemory: "elena_allows_soft_structure" }, { text: "Tell her rest matters more than one paragraph.", relationshipImpact: 3, chemistryImpact: 5, unlocksMemory: "elena_accepts_rest" }] },`]:
  `    { id: "elena_early", type: "early connection", minRelationship: 18, title: "Library Closing Time", prompt: "Elena is racing a deadline as security closes the library. She rubs her temples, the academic pressure and fear of losing control evident in her tight shoulders.", emotionalBeat: "Academic pressure and fear of losing control.", choices: [{ text: "Quietly sit beside her and help organize citations without being asked.", relationshipImpact: 7, chemistryImpact: 6, unlocksMemory: "elena_silent_support" }, { text: "Set a timer and make her take a tea break first.", relationshipImpact: 5, chemistryImpact: 7, unlocksMemory: "elena_allows_soft_structure" }, { text: "Tell her rest matters more than one paragraph.", relationshipImpact: 3, chemistryImpact: 5, unlocksMemory: "elena_accepts_rest" }] },`,

  [`    { id: "elena_reveal", type: "personal reveal", minRelationship: 35, title: "The Fellowship Letter", prompt: "Elena admits she was waitlisted after publicly projecting confidence.", emotionalBeat: "Ambition meets shame.", choices: [{ text: "You are more than one committee decision.", relationshipImpact: 10, chemistryImpact: 8, unlocksMemory: "elena_shared_waitlist" }, { text: "Let me quiz you out loud so we can rebuild confidence.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "elena_oral_drill_ritual" }, { text: "Let's draft an appeal tonight.", checkStat: "corporate", threshold: 30, onSuccess: { relationshipImpact: 7, chemistryImpact: 5 }, onFail: { relationshipImpact: 2, chemistryImpact: 1 } }] },`]:
  `    { id: "elena_reveal", type: "personal reveal", minRelationship: 35, title: "The Fellowship Letter", prompt: "Elena admits she was waitlisted for the fellowship. She looks away, ambition warring with shame as she silently asks if you still see her the same way.", emotionalBeat: "Ambition meets shame.", choices: [{ text: "Tell her she is more than one committee decision.", relationshipImpact: 10, chemistryImpact: 8, unlocksMemory: "elena_shared_waitlist" }, { text: "Let me quiz you out loud so we can rebuild confidence.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "elena_oral_drill_ritual" }, { text: "Let's draft an appeal tonight.", checkStat: "corporate", threshold: 30, onSuccess: { relationshipImpact: 7, chemistryImpact: 5, unlocksMemory: "elena_appeal_victory" }, onFail: { relationshipImpact: 2, chemistryImpact: 1, unlocksMemory: "elena_appeal_failure" } }] },`,

  [`    { id: "elena_conflict", type: "conflict", minRelationship: 52, title: "Missed Dinner", prompt: "She cancels abruptly and sounds cold by text.", emotionalBeat: "Defensive detachment.", choices: [{ text: "Reply with sarcasm.", relationshipImpact: -6, chemistryImpact: -4, futureCallback: "elena_deadline_argument" }, { text: "Ask if she is okay first.", relationshipImpact: 6, chemistryImpact: 7, unlocksMemory: "elena_trusts_player_under_stress" }, { text: "Send a calm note: no punishment, just honesty when ready.", relationshipImpact: 4, chemistryImpact: 6, futureCallback: "elena_repair_letter" }] },`]:
  `    { id: "elena_conflict", type: "conflict", minRelationship: 52, title: "Missed Dinner", prompt: "She cancels dinner abruptly, her texts sounding unusually cold. The defensive detachment feels like a wall she built to protect herself from being a disappointment.", emotionalBeat: "Defensive detachment.", choices: [{ text: "Reply with sarcasm, matching her coldness.", relationshipImpact: -6, chemistryImpact: -4, futureCallback: "elena_deadline_argument" }, { text: "Ask if she is okay first, ignoring the brush-off.", relationshipImpact: 6, chemistryImpact: 7, unlocksMemory: "elena_trusts_player_under_stress" }, { text: "Send a calm note: no punishment, just honesty when she is ready.", relationshipImpact: 4, chemistryImpact: 6, futureCallback: "elena_repair_letter" }] },`,

  // BRAD
  [`    { id: "brad_intro", type: "introduction", minRelationship: 0, title: "Post-Workout Truth", prompt: "Brad asks what discipline means when no one is watching.", emotionalBeat: "Confidence masking insecurity and liking explicit praise.", choices: [{ text: "Consistency beats intensity.", relationshipImpact: 8, chemistryImpact: 7 }, { text: "Give him a playful pep-talk challenge.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "brad_likes_motivation_talk" }, { text: "Flex for him and boast.", checkStat: "fitness", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 5 }, onFail: { relationshipImpact: -1, chemistryImpact: -2 } }] },`]:
  `    { id: "brad_intro", type: "introduction", minRelationship: 0, title: "Post-Workout Truth", prompt: "Brad wipes sweat from his brow, his confidence masking a sudden need for approval. He asks what discipline really means to you when no one is watching.", emotionalBeat: "Confidence masking insecurity and liking explicit praise.", choices: [{ text: "Tell him that true consistency beats flashy intensity.", relationshipImpact: 8, chemistryImpact: 7, unlocksMemory: "brad_respects_consistency" }, { text: "Give him a playful pep-talk challenge.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "brad_likes_motivation_talk" }, { text: "Flex for him and boast about your own PRs.", checkStat: "fitness", threshold: 35, onSuccess: { relationshipImpact: 6, chemistryImpact: 5, unlocksMemory: "brad_impressed_by_flex" }, onFail: { relationshipImpact: -1, chemistryImpact: -2, futureCallback: "brad_awkward_flex" } }] },`,

  [`    { id: "brad_early", type: "early connection", minRelationship: 18, title: "Meal Prep Night", prompt: "His sponsor requests a live cooking stream.", emotionalBeat: "Bravado under pressure.", choices: [{ text: "Cook together off-camera first.", relationshipImpact: 7, chemistryImpact: 6, unlocksMemory: "brad_trusts_player_prep" }, { text: "Let him lead while you follow his routine exactly.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "brad_controlled_kitchen" }, { text: "Push him to wing it live.", relationshipImpact: -2, chemistryImpact: 1, futureCallback: "brad_stream_disaster" }] },`]:
  `    { id: "brad_early", type: "early connection", minRelationship: 18, title: "Meal Prep Night", prompt: "Brad's sponsor requested a live cooking stream. Underneath the bravado, the pressure is getting to him, and he needs someone he trusts to anchor the kitchen.", emotionalBeat: "Bravado under pressure.", choices: [{ text: "Cook together off-camera first to calm his nerves.", relationshipImpact: 7, chemistryImpact: 6, unlocksMemory: "brad_trusts_player_prep" }, { text: "Let him lead while you follow his routine exactly.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "brad_controlled_kitchen" }, { text: "Push him to wing it live and just be charismatic.", relationshipImpact: -2, chemistryImpact: 1, futureCallback: "brad_stream_disaster" }] },`,

  [`    { id: "brad_reveal", type: "personal reveal", minRelationship: 35, title: "Old Injury Scare", prompt: "Brad admits he is terrified of becoming irrelevant if his body fails.", emotionalBeat: "Vulnerability beneath bravado.", choices: [{ text: "Your worth is not your PR numbers.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "brad_identity_beyond_fitness" }, { text: "Let me spot you through recovery drills at your pace.", relationshipImpact: 7, chemistryImpact: 8 }, { text: "Train harder and silence doubters.", checkStat: "confidence", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 4 }, onFail: { relationshipImpact: -3, chemistryImpact: -2 } }] },`]:
  `    { id: "brad_reveal", type: "personal reveal", minRelationship: 35, title: "Old Injury Scare", prompt: "Brad rubs his injured shoulder, finally dropping the invincible act. He admits he's terrified of becoming irrelevant if his body fails him.", emotionalBeat: "Vulnerability beneath bravado.", choices: [{ text: "Tell him his worth is not tied to his PR numbers.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "brad_identity_beyond_fitness" }, { text: "Let me spot you through recovery drills at your pace.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "brad_recovery_drills" }, { text: "Tell him to train harder and silence the doubters.", checkStat: "confidence", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 4, unlocksMemory: "brad_pushed_through" }, onFail: { relationshipImpact: -3, chemistryImpact: -2, futureCallback: "brad_injury_worsened" } }] },`,

  [`    { id: "brad_conflict", type: "conflict", minRelationship: 52, title: "Skipped Session", prompt: "You miss a planned gym meet and Brad feels dismissed.", emotionalBeat: "Fear of not being prioritized.", choices: [{ text: "Defend yourself aggressively.", relationshipImpact: -6, chemistryImpact: -5 }, { text: "Apologize and ask what it triggered for him.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "brad_opens_about_abandonment" }, { text: "Offer to rebuild trust with a realistic shared routine.", relationshipImpact: 5, chemistryImpact: 6, futureCallback: "brad_repair_schedule" }] },`]:
  `    { id: "brad_conflict", type: "conflict", minRelationship: 52, title: "Skipped Session", prompt: "You miss a planned gym meet and Brad immediately shuts down. His fear of not being prioritized flares up into a sharp, sudden argument.", emotionalBeat: "Fear of not being prioritized.", choices: [{ text: "Defend yourself aggressively against his accusations.", relationshipImpact: -6, chemistryImpact: -5, futureCallback: "brad_aggression_memory" }, { text: "Apologize and gently ask what your absence triggered for him.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "brad_opens_about_abandonment" }, { text: "Offer to rebuild trust with a realistic shared routine.", relationshipImpact: 5, chemistryImpact: 6, futureCallback: "brad_repair_schedule" }] },`,
};

for (const [key, value] of Object.entries(replacements)) {
  if (!content.includes(key)) {
    console.error("COULD NOT FIND:", key.substring(0, 100));
  } else {
    content = content.replace(key, value);
  }
}

fs.writeFileSync(filepath, content);
console.log("Updated Elena and Brad.");
