import fs from 'fs';

const filepath = 'src/data/npcs.js';
let content = fs.readFileSync(filepath, 'utf8');

const replacements = {
  // SOPHIA
  [`    { id: "sophia_intro", type: "introduction", minRelationship: 0, title: "Mirror Talk", prompt: "Sophia asks if you like her public image or her actual self.", emotionalBeat: "Status anxiety and a taste for admiration.", choices: [{ text: "I like who you are off-camera.", relationshipImpact: 9, chemistryImpact: 9, unlocksMemory: "sophia_seen_without_filter" }, { text: "Give her a sincere compliment and ask what she wants tonight.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "sophia_praise_with_care" }, { text: "Your brand is elite.", checkStat: "style", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 4 }, onFail: { relationshipImpact: -2, chemistryImpact: -2 } }] },`]:
  `    { id: "sophia_intro", type: "introduction", minRelationship: 0, title: "Mirror Talk", prompt: "Sophia catches your eye in the mirror, turning away from her ring light. She asks, voice surprisingly quiet, if you prefer her public image or her actual self.", emotionalBeat: "Status anxiety and a taste for admiration.", choices: [{ text: "Tell her you like who she is when the cameras are off.", relationshipImpact: 9, chemistryImpact: 9, unlocksMemory: "sophia_seen_without_filter" }, { text: "Give her a sincere compliment and ask what she wants tonight.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "sophia_praise_with_care" }, { text: "Tell her the brand is elite, playing into the persona.", checkStat: "style", threshold: 40, onSuccess: { relationshipImpact: 5, chemistryImpact: 4, unlocksMemory: "sophia_brand_validated" }, onFail: { relationshipImpact: -2, chemistryImpact: -2, futureCallback: "sophia_felt_misunderstood" } }] },`,

  [`    { id: "sophia_early", type: "early connection", minRelationship: 18, title: "Late Night Edit", prompt: "Sophia needs someone to help review a contract, but her usual team is busy.", emotionalBeat: "Seeking a partner, not an employee.", choices: [{ text: "Read the fine print for her.", relationshipImpact: 7, chemistryImpact: 6, unlocksMemory: "sophia_trusts_player_with_business" }, { text: "Offer to handle dinner while she reads.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "sophia_dinner_ritual" }, { text: "Tell her to just sign it if the money is good.", relationshipImpact: 1, chemistryImpact: 0 }] },`]:
  `    { id: "sophia_early", type: "early connection", minRelationship: 18, title: "Late Night Edit", prompt: "Sophia drops a massive contract on her desk. She looks completely overwhelmed and asks you to help her decipher it, needing someone outside her payroll she can actually trust.", emotionalBeat: "Seeking a partner, not an employee.", choices: [{ text: "Sit beside her and read the fine print together.", relationshipImpact: 7, chemistryImpact: 6, unlocksMemory: "sophia_trusts_player_with_business" }, { text: "Offer to handle dinner while she reads, taking the pressure off.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "sophia_dinner_ritual" }, { text: "Tell her to just sign it if the money is good.", relationshipImpact: 1, chemistryImpact: 0, futureCallback: "sophia_dismissive_advice" }] },`,

  [`    { id: "sophia_reveal", type: "personal reveal", minRelationship: 35, title: "Contract Clause", prompt: "Sophia confesses a brand wants to script her personal life.", emotionalBeat: "Sincerity beneath performance.", choices: [{ text: "Protect your boundaries first.", relationshipImpact: 10, chemistryImpact: 8, unlocksMemory: "sophia_boundary_priority" }, { text: "Draft three non-negotiables and rehearse saying no.", relationshipImpact: 7, chemistryImpact: 7 }, { text: "Take the money and adapt.", checkStat: "negotiation", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 3 }, onFail: { relationshipImpact: -3, chemistryImpact: -2 } }] },`]:
  `    { id: "sophia_reveal", type: "personal reveal", minRelationship: 35, title: "Contract Clause", prompt: "Sophia pours herself a drink, confessing a major brand wants to script her personal life. The glossy performance drops entirely, revealing deep, quiet sincerity.", emotionalBeat: "Sincerity beneath performance.", choices: [{ text: "Tell her to protect her boundaries first.", relationshipImpact: 10, chemistryImpact: 8, unlocksMemory: "sophia_boundary_priority" }, { text: "Draft three non-negotiables and rehearse saying no.", relationshipImpact: 7, chemistryImpact: 7, unlocksMemory: "sophia_practiced_boundaries" }, { text: "Tell her to take the money and adapt.", checkStat: "negotiation", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 3, unlocksMemory: "sophia_money_focus" }, onFail: { relationshipImpact: -3, chemistryImpact: -2, futureCallback: "sophia_felt_pushed" } }] },`,

  [`    { id: "sophia_conflict", type: "conflict", minRelationship: 52, title: "Leaked Photos Night", prompt: "After a leak, she accuses everyone of chasing clout.", emotionalBeat: "Humiliation and distrust.", choices: [{ text: "Argue she is overreacting.", relationshipImpact: -7, chemistryImpact: -5 }, { text: "Offer privacy and ask what support looks like.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "sophia_safe_with_player" }, { text: "Protect her space and screen all messages for one night.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "sophia_crisis_protocol" }] },`]:
  `    { id: "sophia_conflict", type: "conflict", minRelationship: 52, title: "Leaked Photos Night", prompt: "After a massive privacy leak, she shuts everyone out, aggressively accusing the whole room of chasing clout. Humiliation and distrust radiate from her.", emotionalBeat: "Humiliation and distrust.", choices: [{ text: "Argue she is overreacting.", relationshipImpact: -7, chemistryImpact: -5, futureCallback: "sophia_defensive_argument" }, { text: "Offer complete privacy and ask what support looks like right now.", relationshipImpact: 8, chemistryImpact: 9, unlocksMemory: "sophia_safe_with_player" }, { text: "Protect her space and screen all messages for one night.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "sophia_crisis_protocol" }] },`,

  // MARCUS
  [`    { id: "marcus_intro", type: "introduction", minRelationship: 0, title: "Calendar Tetris", prompt: "Marcus offers a ten-minute coffee between investor calls.", emotionalBeat: "Control as survival; he relaxes when someone can take the lead.", choices: [{ text: "Use the ten minutes fully, no posturing.", relationshipImpact: 8, chemistryImpact: 7 }, { text: "Take charge and set the agenda for him.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "marcus_relieved_by_structure" }, { text: "Pitch yourself aggressively.", checkStat: "corporate", threshold: 45, onSuccess: { relationshipImpact: 6, chemistryImpact: 4 }, onFail: { relationshipImpact: -2, chemistryImpact: -2 } }] },`]:
  `    { id: "marcus_intro", type: "introduction", minRelationship: 0, title: "Calendar Tetris", prompt: "Marcus checks his watch twice before offering a strict ten-minute coffee between investor calls. The control is a survival mechanism, but he relaxes slightly when you lead the conversation.", emotionalBeat: "Control as survival; he relaxes when someone can take the lead.", choices: [{ text: "Use the ten minutes fully, zero posturing.", relationshipImpact: 8, chemistryImpact: 7, unlocksMemory: "marcus_respects_directness" }, { text: "Take charge and set the agenda for him.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "marcus_relieved_by_structure" }, { text: "Pitch yourself aggressively.", checkStat: "corporate", threshold: 45, onSuccess: { relationshipImpact: 6, chemistryImpact: 4, unlocksMemory: "marcus_impressed_by_pitch" }, onFail: { relationshipImpact: -2, chemistryImpact: -2, futureCallback: "marcus_wasted_time" } }] },`,

  [`    { id: "marcus_early", type: "early connection", minRelationship: 18, title: "Midnight Spreadsheet", prompt: "You find him still working at 2AM and running on espresso.", emotionalBeat: "Exhaustion disguised as drive.", choices: [{ text: "Bring food and sit quietly with him.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "marcus_allows_care" }, { text: "Tell him to hand over the laptop for twenty minutes of forced rest.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "marcus_structured_shutdown" }, { text: "Tell him to push through and finish.", relationshipImpact: -1, chemistryImpact: 1 }] },`]:
  `    { id: "marcus_early", type: "early connection", minRelationship: 18, title: "Midnight Spreadsheet", prompt: "You find Marcus still working at 2AM, running on espresso and sheer willpower. His exhaustion is heavily disguised as drive, but his hands are shaking.", emotionalBeat: "Exhaustion disguised as drive.", choices: [{ text: "Bring food and sit quietly with him without demanding his attention.", relationshipImpact: 7, chemistryImpact: 8, unlocksMemory: "marcus_allows_care" }, { text: "Tell him to hand over the laptop for twenty minutes of forced rest.", relationshipImpact: 6, chemistryImpact: 7, futureCallback: "marcus_structured_shutdown" }, { text: "Tell him to push through and finish.", relationshipImpact: -1, chemistryImpact: 1, futureCallback: "marcus_burnt_out" }] },`,

  [`    { id: "marcus_reveal", type: "personal reveal", minRelationship: 35, title: "The Panic Draft", prompt: "Marcus admits he does not remember his last day off.", emotionalBeat: "Fear of losing control.", choices: [{ text: "You are allowed to be human, not just useful.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "marcus_seen_when_tired" }, { text: "Build him a clear stop-time ritual for each night.", relationshipImpact: 7, chemistryImpact: 7 }, { text: "Optimize your schedule harder.", checkStat: "finance", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 3 }, onFail: { relationshipImpact: -3, chemistryImpact: -2 } }] },`]:
  `    { id: "marcus_reveal", type: "personal reveal", minRelationship: 35, title: "The Panic Draft", prompt: "Marcus drops his pen, finally admitting he cannot remember his last day off. The admission reveals a deep-seated fear of losing control if he ever stops moving.", emotionalBeat: "Fear of losing control.", choices: [{ text: "Remind him he is allowed to be human, not just useful.", relationshipImpact: 10, chemistryImpact: 9, unlocksMemory: "marcus_seen_when_tired" }, { text: "Build him a clear stop-time ritual for each night.", relationshipImpact: 7, chemistryImpact: 7, unlocksMemory: "marcus_night_ritual" }, { text: "Tell him to optimize his schedule harder.", checkStat: "finance", threshold: 40, onSuccess: { relationshipImpact: 4, chemistryImpact: 3, unlocksMemory: "marcus_schedule_optimized" }, onFail: { relationshipImpact: -3, chemistryImpact: -2, futureCallback: "marcus_optimization_failed" } }] },`,

  [`    { id: "marcus_conflict", type: "conflict", minRelationship: 52, title: "Do Not Disturb", prompt: "He silences your messages during a board crisis.", emotionalBeat: "Work reflex overriding intimacy.", choices: [{ text: "Accuse him of choosing work over you.", relationshipImpact: -6, chemistryImpact: -4 }, { text: "Name your hurt and ask for repair timing.", relationshipImpact: 7, chemistryImpact: 8, futureCallback: "marcus_repair_conversation" }, { text: "Set a communication protocol for crisis days.", relationshipImpact: 5, chemistryImpact: 6, unlocksMemory: "marcus_crisis_protocol" }] },`]:
  `    { id: "marcus_conflict", type: "conflict", minRelationship: 52, title: "Do Not Disturb", prompt: "During a board crisis, he ruthlessly silences your messages. His work reflex completely overrides intimacy, leaving you feeling shut out.", emotionalBeat: "Work reflex overriding intimacy.", choices: [{ text: "Accuse him of choosing work over you.", relationshipImpact: -6, chemistryImpact: -4, futureCallback: "marcus_accusation_fight" }, { text: "Name your hurt and ask for a specific time to repair.", relationshipImpact: 7, chemistryImpact: 8, futureCallback: "marcus_repair_conversation" }, { text: "Set a communication protocol for crisis days.", relationshipImpact: 5, chemistryImpact: 6, unlocksMemory: "marcus_crisis_protocol" }] },`
};

for (const [key, value] of Object.entries(replacements)) {
  if (!content.includes(key)) {
    console.error("COULD NOT FIND:", key.substring(0, 100));
  } else {
    content = content.replace(key, value);
  }
}

fs.writeFileSync(filepath, content);
console.log("Updated Sophia and Marcus.");
